ARCHS = arm64 arm64e

INSTALL_TARGET_PROCESSES = Preferences

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = UpdateBlockr

UpdateBlockr_FILES = Tweak.xm
UpdateBlockr_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
