#!/bin/bash
start=$(date +%s) #job start time

echo "Started.."
echo "1/3"

cat << EOF
Oh shit! Here go again
- Carl Johnson
EOF
# Sync with Github
cd /var/mobile/Documents/Github/home
git pull 2> /dev/null
#------
cd /private/var/mobile/Documents/Github/repo
git pull 2> /dev/null
#------

echo "2/3"

cd /private/var/mobile/Documents/Github/repo

rm {Packages{,.xz,.gz,.bz2,.zst},Release{,.gpg}} 2> /dev/null

apt-ftparchive packages ./debians > Packages
    
gzip -c9 Packages > Packages.gz
xz -c9 Packages > Packages.xz
zstd -c19 Packages > Packages.zst
bzip2 -c9 Packages > Packages.bz2
apt-ftparchive release -c ./assets/repo/repo.conf . > Release

echo "3/3"

#---Push stuff---#
cd /var/mobile/Documents/Github/repo
git add *
git commit -a -m "Updated."
git push 
#---Push stuff---#
cd /var/mobile/Documents/Github/home
git add *
git commit -a -m "Updated."
git push

end=$(date +%s) #job finish time
ptime=$(expr $end - $start)
echo "Done! in $ptime seconds" #Result

echo "3/3"
echo "Completed in $ptime"