#! /bin/zsh

start=$(date +%s) #job start time

cat << EOF
Oh shit! Here go again
- Carl Johnson
EOF

cd /var/mobile/Documents/Github/home
git pull
pwd 
git add *
git commit -a -m "Updated."
git push 

echo "Upload Completed"

clear 

cat << EOF
Oh shit! Here go again
- Carl Johnson
EOF

cd /private/var/mobile/Documents/Github/repo
git pull

/var/mobile/Documents/Github/repo/updaterepo.sh

git add *

#echo "Bir açıklama ekle"
#read not
#git commit -a -m "$not"
git commit -a -m "Updated."
echo "Upload Started..."
git push
end=$(date +%s) #job finish time
ptime=$(expr $end - $start)

echo "Upload completed in $ptime seconds"
 