#! /bin/zsh

cat << EOF
Oh shit! Here go again
- Carl Johnson
EOF

cd /var/mobile/Documents/Github/home
git pull
git add /var/mobile/Documents/Github/home
git commit -a -m "Updated."
git push 

echo "Upload Completed"

clear 

cat << EOF
Oh shit! Here go again
- Carl Johnson
EOF

cd /private/var/mobile/Documents/Github/repo
git pull
#
#/var/mobile/Documents/Github/repo/updaterepo.sh
#
git add /private/var/mobile/Documents/Github/repo

echo "Bir açıklama ekle"
read not
git commit -a -m "$not"

echo "Upload Started..."
git push
echo "Upload Completed..."
