#! /bin/bash
cat << EOF
Önceki kurulumlardan kalan lisans dosyaları kaldırılıyor. Tamam.
EOF
rm /var/mobile/Library/Preferences/com.reddoorendeavors.enclave.plist

lisans=/var/mobile/Library/Preferences/com.reddoorendeavors.enclave.plist
if test -f $"lisans";then
echo "Hata!."
else 
echo "İşlem başarıyla tamamlandı çıkış kodu 0."
fi
exit