name: Update Packages

permissions:
  contents: write
  pages: write
  id-token: write

on: [push]
jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Update Packages
        id: update_packages
        run: | 
          chmod +x update_all.bash
          ./update_all.bash

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -am "Packages updated. <Auto Action>"
          git push