name: Update Full

permissions:
  contents: write
  pages: write
  id-token: write

on: [push]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Update Packages
        run: | 
          chmod +x update_all.bash
          ./update_all.bash
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
            publish_branch: main
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: .